language: scala
jdk:
- oraclejdk8
scala:
- 2.11.4

after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sbt ++$TRAVIS_SCALA_VERSION
  publish test:publish
env:
  global:
  - secure: BfVMC+TA2YPEcdOj4HS2rqnndzgbaCUaMNfRQA0ra39Ia1tdoSwcO8g/4hGsEg04KuX526ptbbjcb6Rduz6eZrgoc9G7sIrnmpgWXa2fHBxEnWEL6ZdUZFOrKtsUX5yQwJJC9dEIyQsY0xQJlpFPP/Ng9p97lKqajTlrgcCq42LRMJ1yuKguzv2AqMU9t7Io2axFDtNVuqOt+F/BWhxDrxp+N7e5kanNZcS/bopYW/M3uWvKSrGnSPBdkkayAUsnPLCA2DMD007MNm2G3fuUojrbRebLPwBFDXVQXHZMw672eVjW2x/2TS0E2nMnQoGF1bb2quX2YBVXGCy4+jL5FxLRz71p82WTwSKXcslqeOWBBTwmsW2tQlH0PaWSil/EBLqYpid7irjLmao5if76l2hFpGa/K71awMARXKIWLYqvLk3zUKcwSvvq2If0BTb4PpVoNyu3pmBAojXqim1OPXS5dwT027+tDO9sdRSb7aWaDmpMar7ct67fg876rXIP3wePHMp12uwYnQtNccotTqEeq1sCY1Y/O1OCYHbYFiABshPr4QvdnjAgDzxMNGhH9FqAElAKTCKzhVvFz39ZwHp6SlpjctrPan8t8SftaY1U9IuENaULKCf7Cx97CXQIhFAQgS6M1dpYzgVs9cdDSX9mjPFXOj9y5CmrKQVu6Bk=
  - secure: EjpPVhxSHLqN1A+fqAoMF/aNwWprMvxU2/og3GxoGtZ7v2arb0SdvFjNLCxLtx3g6rFDeRu3r2iRYMO+n6rd6CcSgaHVaYSLjO19QBdZHKj3+fFS/xzAUdR7AQAfnDIFK+2ImnR9dhkFhJQnIEo/e/W9B24blTKedNthI9V5qiZVUGPI4vttgO9YlyHIC0HOblGR/HPyICwR6zyoscbKFhKf7BhClfnb2lmlPYgGJQW5O2da2/u8Z0IZG909mrc37egF8+1Qv8lncHr477Xk7ACEBher6mQJ8F2mHwzvfwmya/ghYEebt/woiQOVdH2+p4+LdUvzTEdDQXzHcmRIzhIKgelZn65fcxnXIyqDa6IBxmuhsfnrrkKQKgWbjPRn6Ffj4gbNhVlBt7Glte+E62hbzJsG2ZhDsc9d2xZ3KCuSTpPGB9EC+JGcqwiSznj/k0PWDQ+Q6NwTY/2wwzWczMYF5YcWqE05cUhLQWwaC9gH46i2MwEO+TxhdBilZEStI4uWF4GJ1Q2UQjvzZBh0nNfK0ofwDoCNHSlOcETAzapD0YuIX2E2mJMMwWipHsuq4MqsPuUtTrpKOU6xrimzVJE8BeKfRaKO0uYooJsJ8XA6iIIWJHImV53BVSsGHr3y6F58Ryq1V0f8Y2L9RVCKT+KsRrtD3Ww28Y/GG2D8IXM=
